-- Schema for Personal Data Protection Law (PDPL) Training Feedback (Surabaya, 16 April 2026)

-- Create table for feedback submissions
create table pdpl_surabaya_training_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Personal Info
  full_name text not null,
  company_name text not null,
  division_role text not null,
  email text,
  phone_number text,
  
  -- Options Base
  opt_materi_kesesuaian text not null,
  opt_trainer_kemampuan text not null,
  opt_materi_kualitas text not null,
  opt_metode_penyampaian text not null,
  opt_fasilitas_media text not null,
  opt_efektivitas_penyampaian text not null,
  opt_tingkat_pemahaman text not null,
  opt_kepuasan_keseluruhan text not null,
  
  -- Yes/No Base
  yt_kebutuhan_layanan text not null,
  yt_bersedia_info text not null,
  yt_bersedia_dokumentasi text not null,
  
  -- Comments Base
  ur_kritik_saran text,
  ur_hal_baik text,
  ur_saran_selanjutnya text,
  ur_kebutuhan_topik text
);

-- Enable RLS
alter table pdpl_surabaya_training_feedback enable row level security;

-- Allow inserts from anon and authenticated
create policy "Enable insert for everyone" on pdpl_surabaya_training_feedback for insert with check (true);

-- Allow select only for authenticated (if needed)
create policy "Enable read access for authenticated users only" on pdpl_surabaya_training_feedback for select using (auth.role() = 'authenticated');

-- Note: Make sure the rate limitation tables (rate_limit_tokens and submission_logs) already exist,
-- if this is the same Supabase project. If not, refer to previous schema files.
